#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="css/style.css">
#+OPTIONS: num:nil toc:nil html-postamble:nil

#+TITLE: Causal Desires

#+HTML: <q> To model is human; to model causally, divine </q>

"Why?" - the perennial question beloved by children, philosphers, journalists alike; echoing from schoolyard to courtroom. It belies a basic human desire: effect should have cause, preferably one compatible with our undestanding of the world.

"Why" is, however, not an easy question to answer. Aristotle named four kinds of causes and explored their relations, among each other and with effect. Today, undergraduates dutifully learn that correlation is not causation. In Pearl's work on causal calculus and reasoning, this history and the 'causal revolution' is thoroughly explored [fn:1]. In Pearl's causal calculus, the conclusion of causality relies (in part) on assumptions provided by the model-maker, for example that relevant mediator and confounder variables have been properly identified. While this makes some uncomfortable, such as those with an aesthetic preference for scientific conclusions which any rational observer would accept (given a number of axioms), it makes one thing explicit: causality is a property of a model - a point detailed in Norton's [[https://www.pitt.edu/~jdnorton/papers/003004.pdf]['Causation as Folk Science']]. 

The principle concern of causal calculus is non-sequential decision making [fn:2], questions like 'does smoking cause cancer' or 'does this intervention improve this health outcome'. However, many decisions of daily life - whether we do something special for our loved ones, what we make for dinner, whether we go exercise - are sequential, where the action we take affects the world. The world, in turn, affects us and our propensity for certain actions. 

Consider a rational agent choosing actions to achieve a certain outcome through the use of an internal model, action -> outcome. If I do this, then that happens; a sort of counterfactual exploration which is one theory of mind [fn:4]. This forward model impacts the agent's actions, but has a causality which may be incomplete.

An incomplete causal story leaves room for plausible stories which invert the causality - where the effect is presented as a cause. The self-fullfilling prophecy is a sort of causality inversion: instead of a certain future causing a prediction to be made (and, somehow, transported back in time), the prophecy becomes the cause of the future. Causality inversion seems to enjoy a degree of popularity, typically as a minority or contrarian view. 

[fn:1] Pearl and Mackenzie, 'The Book of Why: The New Science of Cause and Effect', a number of shorter introductions [[https://www.inference.vc/untitled/][available]].
[fn:2] Although the causal graph can be extended to consider a time series, this is decidedly not the focus of the text. 
[fn:4] This theory of decision making is not the only one; see, e.g. [[https://arxiv.org/abs/1901.01291]['On the Utility of Model Learning in HRI']] by Choudhury, et al.

** Love
Typical model: Love -> loving behavior
The typical folk wisdom is that love causes loving actions, whereas the feelings we assosciate with love could also be productively viewed as resulting from loving actions [fn:3].  This presents the alternative view that feelings of love emerge from and are reinforced by loving actions - that we inhabit our expressions. 

[fn:3] Nussbaum, "Love and the Individual: Romantic Rightness and Platonic Aspiration"

** Eternal salvation
Typical model: Good actions -> eternal salvation

A common religious view of good actions and eternal salvation is that good actions cause eternal salvation. The Puritans, especially Calvinists, typically espouse a form of predestination: that one does not choose salvation; 'the privilege of choice is God's alone'. Good behavior *results* from being elected for salvation, but does not *cause* it.

How does such a viewpoint affect the person who holds it? Someone contemplating an action which is, by their judgement, 'not good', and weighing this action with respect to the eternal salvation of their soul, it seems that predestination would lend a certain apathy, for their salvation is fixed. This seems to encourage a strong bifurcation in behavior: one who believes themselves destined for damnation has little reason to not act accordingly.

